name: send mail

on:
  schedule:
    - cron: "28 23 * * *"
#   push:
#     branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout repo content
      uses: actions/checkout@v2
    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: install dependencies
      run: |
        pip install jinja2 ddddocr requests pillow beautifulsoup4 lxml
    - name: execute py script
      run: |
        python main.py -u $Username -p $Password
      env:
        Username: ${{ secrets.HHU_ID }}
        Password: ${{ secrets.HHU_PASSWORD }}
    - name: send email
      uses: dawidd6/action-send-mail@v2
      with:
        server_address: smtp.163.com
        server_port: 465
        username: ${{ secrets.MAIL_USERNAME }}
        password: ${{ secrets.MAIL_PASSWORD }}
        subject: 空闲教室
        body: file://template/result.html
        to: wlonestar@163.com
        from: GitHub Actions
        content_type: text/html

